# _config.yml
title: Portfolio de Compétences

execute:
  execute_notebooks: cache
  timeout: 300

html:
  favicon: images/profile.png

sphinx:
  config:
    html_theme: "sphinx_book_theme"
    html_theme_options:
      repository_url: https://github.com/AIMELEBONDEV/portfolio-book
      use_repository_button: true
      show_prev_next: true
      logo_only: true   # Affiche uniquement le logo, nécessaire pour CSS
      extra_footer: |
        <div style="background-color:#123456; color:white; padding:10px; width:23cm; display:flex; justify-content:space-between; align-items:center; font-size:0.85em; border-radius:5px;">
          <div style="display:flex; align-items:center; gap:10px;">
            <img src="images/ADJEGUEDE_PHOTO.jpg" alt="Photo" style="height:40px; width:40px; border-radius:50%;">
            <span>💻 Retrouvez-moi sur : 
              <a href="https://www.linkedin.com/in/aimeadjeguede/" target="_blank" style="color:white; text-decoration:none; margin:0 5px;">LinkedIn</a> |
              <a href="https://github.com/AIMELEBONDEV" target="_blank" style="color:white; text-decoration:none; margin:0 5px;">GitHub</a>
            </span>
          </div>
          <span>© 2025 Aimé ADJEGUEDE</span>
        </div>

    extra_navbar: |
      <style>
        /* Fond général doux */
        body { background-color: #f4f5f7 !important; font-family: 'Segoe UI', Arial, sans-serif; }

        /* Contenu principal */
        .bd-content { 
          max-width: 900px !important; 
          margin: 50px auto !important; 
          padding: 35px !important; 
          background: #ffffff !important; 
          border-radius: 15px !important; 
          box-shadow: 0 10px 25px rgba(0,0,0,0.08) !important; 
        }

        /* Titres */
        h1, h2, h3, h4 { color: #1f3c88 !important; }

        /* Paragraphes et liens */
        p { text-align: justify; font-size: 1.05rem; line-height: 1.7; color: #333 !important; }
        a { color: #1f3c88 !important; text-decoration: none; }
        a:hover { text-decoration: underline; }

        /* Code et blocs */
        pre, .highlight { background-color: #eef2f7 !important; padding: 1rem; border-radius: 10px; overflow-x: auto; }
        .admonition { border-left: 4px solid #1f3c88; background-color: #e6edfa; padding: 1rem; border-radius: 6px; margin: 1rem 0; }

        /* Logo dans la navbar */
        .navbar .logo img {
          height: 40px !important;      
          width: 40px !important;       
          border-radius: 50% !important; 
          object-fit: cover;
        }
      </style>
